

on:
  push:
    branches: [main]

name: Azure Login

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
        az webapp list --query "[?state=='Running']"

      # Checks out the repository this file is in
     