name: Docker Image CI

on:
  schedule:
  - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest version
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Check the latest version and push new versions
        shell: bash
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/scripts/get_updates.sh"

          # run script
          "${GITHUB_WORKSPACE}/scripts/get_updates.sh"